### ISSUE TITLE
Annotattions

### ISSUE THREAD

**Issue by LETUSMUYAGA** [SBOHVM/FernandaSanchezRSeries03#2]
Your codes run well. Congratulation

Indeed you have done a good job

But you can add more details on what each code performs 

Example in "Stochastic birth/death population model" practical you can annotate the below code as follows

##creating a dataframe called population.df with the parameters
##count and time 
 population.df <- data.frame(count = initial.count, time = start.time)
 
you co do the same to the final.populations as well and the rest of the codes

**Comment by FernandaSanchezR** [comment]
Thank you! I will include you suggestions.
