### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by richardreeve** [SBOHVM/FernandaSanchezRSeries03#3]
Generally very good, though note that there are no title for the reports. There is no package maintainer in DESCRIPTION, and the package help file is a bit inaccurate. A missing empty line (#') in some of the function help texts means they don't look quite right, and you don't check whether the `actual.infection.rate` is over 1, just the effective rate.

**Comment by FernandaSanchezR** [comment]
Fixed all these issues, thank you!
